<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-41741T4J" ignored="0" name="RetryFailed" tests="4" failures="1" timestamp="2022-09-13T22:00:49 IST" time="0.095" errors="0">
  <testcase name="Test1" time="0.017" classname="retryAnalyzer.RuntimeRetry"/>
  <testcase name="Test2" time="0.002" classname="retryAnalyzer.RuntimeRetry">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.01" classname="retryAnalyzer.RuntimeRetry">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="retryAnalyzer.RuntimeRetry">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryAnalyzer.RuntimeRetry.Test2(RuntimeRetry.java:14)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- RetryFailed -->
